### ISSUE TITLE
Profiler missing some function calls

### ISSUE THREAD

**Issue by kieran-mace** [r-lib/profvis#138]
you can even see this in the package documentation website: http://rstudio.github.io/profvis/

while the png shows the call to `plot`, and shows the time as expected: 
<img width="917" alt="profvis" src="https://user-images.githubusercontent.com/18296227/188214478-c7b83eed-d265-47d2-8d93-385ddd530f60.png">

the actual output omits the call to `plot`: 
![Screenshot_2022-09-02 11 18 44_GTp6JF](https://user-images.githubusercontent.com/18296227/188214634-c9b98105-2d5e-46c4-af7f-4f2382ff8e69.png)

**Comment by hadley** [comment]
That's because the default is to simplify the call stack, by eliminating calls that are typically not that useful. In this case it eliminates the call to `plot()` which unfortunately is overly aggressive, but doesn't substantially change the outputs. You can opt out of this behaviour with `simplify = FALSE`.
