### ISSUE TITLE
profvis() messes up syntax highlighting in Quarto and R Markdown code blocks

### ISSUE THREAD

**Issue by prosoitos** [r-lib/profvis#140]
See issue quarto-dev/quarto-cli#3991 for reproducible example and explanations.

**Comment by wch** [comment]
It looks like the colors are from `textmate.css`. Profvis includes a very old version of highlight.js which doesn't do any scoping -- all `<span>`s are affected by the CSS.

https://github.com/rstudio/profvis/blob/a4ac85ce2fd73f82a3e6deae3989863b2a32db4d/inst/htmlwidgets/lib/highlight/textmate.css

I think this can be fixed by adding `.profvis-code` to the CSS rules.

**Comment by hadley** [comment]
Actual link to underlying issue:  https://github.com/quarto-dev/quarto-cli/issues/3991

Minimal reprex:

````Rmd
---
format: html
---

```{r}
f <- function() {
  pause(0.1)
}
profvis::profvis(f())
```
````
